### PR TITLE
EnderCreeper afraid of cats

### PR DESCRIPTION
**Pull request by DrParadox7**
EnderCreeper drop aggro and teleport away when cats are nearby

### CODE REVIEW

**Comment by DrParadox7** [comment]
**Note:**
Not affected by Thaumic Tinkerer's Feline talisman since we are not using the AI
https://github.com/GTNewHorizons/ThaumicTinkerer/blob/3bb2edda24629f588ab7b05188972a567500c632/src/main/java/thaumic/tinkerer/common/item/kami/ItemCatAmulet.java#L66

**Review by Alastors — APPROVED** [review]
it just makes sense, they're still endermen even if in a different form, they should have the same weaknesses

**Comment by Fabboz** [comment]
i've got that crash, doing mining nothing special. in a biome where spawn cats.

---- Minecraft Crash Report ----
// My bad.

Time: 7/16/23 6:08 PM
Description: Ticking entity

java.lang.AbstractMethodError
	at net.minecraft.world.chunk.Chunk.func_76618_a(Chunk.java:1001)
	at net.minecraft.world.World.func_82733_a(World.java:3230)
	at toast.specialMobs.entity.creeper.EntityEnderCreeper.catNearby(EntityEnderCreeper.java:256)
	at toast.specialMobs.entity.creeper.EntityEnderCreeper.func_70636_d(EntityEnderCreeper.java:140)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:272)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30)
	at net.minecraft.entity.monster.EntityCreeper.func_70071_h_(SourceFile:119)
	at toast.specialMobs.entity.creeper.Entity_SpecialCreeper.func_70071_h_(Entity_SpecialCreeper.java:161)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:1646)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.chunk.Chunk.func_76618_a(Chunk.java:1001)
	at net.minecraft.world.World.func_82733_a(World.java:3230)
	at toast.specialMobs.entity.creeper.EntityEnderCreeper.catNearby(EntityEnderCreeper.java:256)
	at toast.specialMobs.entity.creeper.EntityEnderCreeper.func_70636_d(EntityEnderCreeper.java:140)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:272)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30)
	at net.minecraft.entity.monster.EntityCreeper.func_70071_h_(SourceFile:119)
	at toast.specialMobs.entity.creeper.Entity_SpecialCreeper.func_70071_h_(Entity_SpecialCreeper.java:161)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: SpecialMobs.EnderCreeper (toast.specialMobs.entity.creeper.EntityEnderCreeper)
	Entity ID: 42846
	Entity Name: Ender Creeper
	Entity's Exact location: 12284.50, 72.00, 14094.50
	Entity's Block location: World: (12284,72,14094), Chunk: (at 12,4,14 in 767,880; contains blocks 12272,0,14080 to 12287,255,14095), Region: (23,27; contains chunks 736,864 to 767,895, blocks 11776,0,13824 to 12287,255,14335)
	Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:1646)

**Comment by Ethryan** [comment]
@Fabboz please create a issue post in the main GTNH repository please.

**Comment by Fabboz** [comment]
i'm not playing new horizon modpack

**Pull request merged**
