### PR TITLE
Feint Ghast Retexture

### PR DESCRIPTION
**Pull request by DrParadox7**
I feel like the original feint ghast texture does not convey what it is supposed to be thematically. 
Description according to the author:

_"Faint Ghast The faint ghast is a normal ghast that has almost completely faded from the world. As such, it is almost completely unaffected by the world, allowing it to move freely through blocks to eat your face off. Despite this, we were able to defeat them, but could only recover small amounts of residue to experiment with."_

A green box with red facial expression does not match adequately to that description.
My version has the ghast made with Nether portal smoke to convey the _"almost completely faded from the world. "_ and _"unaffected by the world, allowing it to move freely through block"_ by being mist/ghost like (we do not know the properties of Nether portal smoke so plausibility and magic fill in the gaps).

On top of being more aesthetically pleasing, the new changes help with visibility as it has more overall visible pixels.

I'll attach the before and after pick and you may decide whether this would be more beneficial over the current familiarity players have with our tabagochi ghast.

Old preview
New Preview

### CODE REVIEW

**Comment by Dream-Master** [comment]
looks cool will check ingame

**Comment by DrParadox7** [comment]
Those screenshots took 45 min to take due to their speed and ability to go through blocks. I aim to get you to use that time better than I did so...
Do yourself a favor by using a void dimension like I did in the screenshots above (after repeatedly failing everywhere else) so you can have the best look (even then, they will be faster than you in creative mode so be prepared).

**Comment by Houstonruss** [comment]
My only suggestion is to tone the purple down towards white, so it doesn't look like a tainted mob.

**Comment by Dream-Master** [comment]
Maybe taint in the nether are a nice addition ?

**Comment by DrParadox7** [comment]
But ghasts can't really be tainted can they?

**Comment by Dream-Master** [comment]
nope no taint in nether

**Comment by DrParadox7** [comment]
Besides, the transparency does sets it apart from any other mob like the original

**Comment by DrParadox7** [comment]
Here how it stands out in the nether (ignore the rest of my textures, color scheme remains the same still)

**Comment by Dream-Master** [comment]
@DrParadox7 @Houstonruss ready for merge ?

**Comment by Dream-Master** [comment]
Houston ☢Today at 8:47 AM
its fine

**Pull request merged**
